const colors = require('tailwindcss/colors')

module.exports = {
  content: ['./public/themes/maeva/**/*.php'],
  safelist: [
    'row-maeva-span-1',
    'row-maeva-span-2',
    'row-maeva-span-3',
    'row-maeva-span-4',
    'row-maeva-span-5',
    'row-maeva-span-6',
    'row-maeva-span-7',
    'row-maeva-span-8',
    'row-maeva-span-9',
    'row-maeva-span-10',
    'col-maeva-span-1',
    'col-maeva-span-2',
    'col-maeva-span-3',
    'col-maeva-span-4',
    'col-maeva-span-5',
    'col-maeva-span-6',
    'col-maeva-span-7',
    'col-maeva-span-8',
    'col-maeva-span-9',
    'col-maeva-span-10',

    'md:row-maeva-span-1',
    'md:row-maeva-span-2',
    'md:row-maeva-span-3',
    'md:row-maeva-span-4',
    'md:row-maeva-span-5',
    'md:row-maeva-span-6',
    'md:row-maeva-span-7',
    'md:row-maeva-span-8',
    'md:row-maeva-span-9',
    'md:row-maeva-span-10',
    'md:col-maeva-span-1',
    'md:col-maeva-span-2',
    'md:col-maeva-span-3',
    'md:col-maeva-span-4',
    'md:col-maeva-span-5',
    'md:col-maeva-span-6',
    'md:col-maeva-span-7',
    'md:col-maeva-span-8',
    'md:col-maeva-span-9',
    'md:col-maeva-span-10',

    'xl:row-maeva-span-1',
    'xl:row-maeva-span-2',
    'xl:row-maeva-span-3',
    'xl:row-maeva-span-4',
    'xl:row-maeva-span-5',
    'xl:row-maeva-span-6',
    'xl:row-maeva-span-7',
    'xl:row-maeva-span-8',
    'xl:row-maeva-span-9',
    'xl:row-maeva-span-10',
    'xl:col-maeva-span-1',
    'xl:col-maeva-span-2',
    'xl:col-maeva-span-3',
    'xl:col-maeva-span-4',
    'xl:col-maeva-span-5',
    'xl:col-maeva-span-6',
    'xl:col-maeva-span-7',
    'xl:col-maeva-span-8',
    'xl:col-maeva-span-9',
    'xl:col-maeva-span-10',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    fontFamily: {
      display: ['Gilroy', 'sans-serif'],
      body: ['Graphik', 'sans-serif'],
      title: ['Satisfy', 'sans-serif'],
      texte: ['dita', 'sans-serif'],
    },
    filter: { // defaults to {}
      'none': 'none',
      'grayscale': 'grayscale(1)',
      'invert': 'invert(1)',
      'sepia': 'sepia(1)',
      'blur': 'blur(10px)',
      'brightness': 'brightness(0.1)',
      'custom': 'blur(3px) brightness(0.1)'
    },
    backdropFilter: { // defaults to {}
      'none': 'none',
      'blur': 'blur(10px)',
      'blur2x': 'blur(20px)',
      'blur3x': 'blur(30px)',
      'blur4x': 'blur(40px)',
      'blurfooter': 'blur(30px)',
      'brightness': 'brightness(0.1)',
    },
    colors: { // defaults to {}
      maeva: {
        g50: '#EEEEEE',
        g100: '#E5E5E5',
        g200: '#e5e5e5',
        g300: '#D9D9D9',
        g400: '#B3B3B3',
        g500: '#737373',
        g600: '#333333',
        g700: '#2C2C2C',
        g800: '#191919',
        g900: '#131313',
        g1000: '#0A0A0A',
        g1100: '#010101',
        purple: '#751424',
        pink: '#FCE7EC',
        pinkHot: '#f297ae'
      },
      black: colors.black,
      white: colors.white,
      transparent: 'transparent',
      current: 'currentColor',
    },
    extend: {
      translate: {
        'nav': '-56px',
        'footerbtn': '-40px',
      },
      transitionDuration: {
        '2000': '2000ms',
        '3000': '3000ms',
        '4000': '4000ms',
        '5000': '5000ms',
        '6000': '6000ms',
        '7000': '7000ms',
      },
      scale: {
        '101': '1.01',
        '102': '1.02',
        '103': '1.03',
        '104': '1.04',
      },
      inset: {
        '-4.5': '-1.15rem',
      },
      spacing: {
        '20px': '20px',
        '30px': '30px',
        '40px': '40px',
        '56px': '56px',
        '100px': '100px',
        '200px': '200px',
        '300px': '300px',
        '400px': '400px',
        '500px': '500px',
        '600px': '600px',
        '700px': '700px',
        '800px': '800px',
        '900px': '900px',
        '1000px': '1000px',
        '10vh': '10vh',
        '20vh': '20vh',
        '30vh': '30vh',
        '40vh': '40vh',
        '50vh': '50vh',
        '60vh': '60vh',
        '70vh': '70vh',
        '80vh': '80vh',
        '90vh': '90vh',
        '10vw': '10vw',
        '20vw': '20vw',
        '30vw': '30vw',
        '40vw': '40vw',
        '50vw': '50vw',
        '60vw': '60vw',
        '70vw': '70vw',
        '80vw': '80vw',
        '90vw': '90vw',
        '80%': '80%',
        '85%': '85%',
        '90%': '90%',
        '98%': '98%'
      },
      opacity: {
        '85': '85%'
      },
      gridRow: {
        'maeva-span-1': 'span 1',
        'maeva-span-2': 'span 2',
        'maeva-span-3': 'span 3',
        'maeva-span-4': 'span 4',
        'maeva-span-5': 'span 5',
        'maeva-span-6': 'span 6',
        'maeva-span-7': 'span 7',
        'maeva-span-8': 'span 8',
        'maeva-span-9': 'span 9',
        'maeva-span-10': 'span 10',
      },
      gridColumn: {
        'maeva-span-1': 'span 1',
        'maeva-span-2': 'span 2',
        'maeva-span-3': 'span 3',
        'maeva-span-4': 'span 4',
        'maeva-span-5': 'span 5',
        'maeva-span-6': 'span 6',
        'maeva-span-7': 'span 7',
        'maeva-span-8': 'span 8',
        'maeva-span-9': 'span 9',
        'maeva-span-10': 'span 10',
      }
    }
  },
  variants: {
    filter: ['responsive'], // defaults to ['responsive']
    backdropFilter: ['responsive'], // defaults to ['responsive']
    extend: {},
  },
  plugins: [
    require('tailwindcss-filters'),
  ],
}
