/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
	| 'Pacific/Midway'
	| 'Pacific/Niue'
	| 'Pacific/Honolulu'
	| 'Pacific/Rarotonga'
	| 'America/Anchorage'
	| 'Pacific/Gambier'
	| 'America/Los_Angeles'
	| 'America/Tijuana'
	| 'America/Denver'
	| 'America/Phoenix'
	| 'America/Chicago'
	| 'America/Guatemala'
	| 'America/New_York'
	| 'America/Bogota'
	| 'America/Caracas'
	| 'America/Santiago'
	| 'America/Buenos_Aires'
	| 'America/Sao_Paulo'
	| 'Atlantic/South_Georgia'
	| 'Atlantic/Azores'
	| 'Atlantic/Cape_Verde'
	| 'Europe/London'
	| 'Europe/Berlin'
	| 'Africa/Lagos'
	| 'Europe/Athens'
	| 'Africa/Cairo'
	| 'Europe/Moscow'
	| 'Asia/Riyadh'
	| 'Asia/Dubai'
	| 'Asia/Baku'
	| 'Asia/Karachi'
	| 'Asia/Tashkent'
	| 'Asia/Calcutta'
	| 'Asia/Dhaka'
	| 'Asia/Almaty'
	| 'Asia/Jakarta'
	| 'Asia/Bangkok'
	| 'Asia/Shanghai'
	| 'Asia/Singapore'
	| 'Asia/Tokyo'
	| 'Asia/Seoul'
	| 'Australia/Brisbane'
	| 'Australia/Sydney'
	| 'Pacific/Guam'
	| 'Pacific/Noumea'
	| 'Pacific/Auckland'
	| 'Pacific/Fiji'

export interface Config {
	auth: {
		users: UserAuthOperations
	}
	blocks: {}
	collections: {
		users: User
		media: Media
		blog: Blog
		gallery: Gallery
		services: Service
		testimonials: Testimonial
		'payload-locked-documents': PayloadLockedDocument
		'payload-preferences': PayloadPreference
		'payload-migrations': PayloadMigration
	}
	collectionsJoins: {}
	collectionsSelect: {
		users: UsersSelect<false> | UsersSelect<true>
		media: MediaSelect<false> | MediaSelect<true>
		blog: BlogSelect<false> | BlogSelect<true>
		gallery: GallerySelect<false> | GallerySelect<true>
		services: ServicesSelect<false> | ServicesSelect<true>
		testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>
		'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
		'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
		'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
	}
	db: {
		defaultIDType: number
	}
	globals: {
		homepage: Homepage
	}
	globalsSelect: {
		homepage: HomepageSelect<false> | HomepageSelect<true>
	}
	locale: null
	user: User & {
		collection: 'users'
	}
	jobs: {
		tasks: unknown
		workflows: unknown
	}
}
export interface UserAuthOperations {
	forgotPassword: {
		email: string
		password: string
	}
	login: {
		email: string
		password: string
	}
	registerFirstUser: {
		email: string
		password: string
	}
	unlock: {
		email: string
		password: string
	}
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
	id: number
	updatedAt: string
	createdAt: string
	email: string
	resetPasswordToken?: string | null
	resetPasswordExpiration?: string | null
	salt?: string | null
	hash?: string | null
	loginAttempts?: number | null
	lockUntil?: string | null
	sessions?:
		| {
				id: string
				createdAt?: string | null
				expiresAt: string
		  }[]
		| null
	password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
	id: number
	alt?: string | null
	updatedAt: string
	createdAt: string
	url?: string | null
	thumbnailURL?: string | null
	filename?: string | null
	mimeType?: string | null
	filesize?: number | null
	width?: number | null
	height?: number | null
	focalX?: number | null
	focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
	id: number
	title: string
	/**
	 * URL de l'article (ex: conseils-maquillage-mariage)
	 */
	slug: string
	featuredImage?: (number | null) | Media
	/**
	 * Court résumé de l'article (affiché dans les listings)
	 */
	excerpt?: string | null
	content: {
		root: {
			type: string
			children: {
				type: any
				version: number
				[k: string]: unknown
			}[]
			direction: ('ltr' | 'rtl') | null
			format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
			indent: number
			version: number
		}
		[k: string]: unknown
	}
	category: 'conseils-maquillage' | 'nail-art' | 'tutoriels' | 'actualites' | 'collections' | 'mariages-evenements'
	tags?:
		| {
				tag: string
				id?: string | null
		  }[]
		| null
	publishedDate: string
	/**
	 * Laisser vide pour Maeva Cinquin par défaut
	 */
	author?: (number | null) | User
	status: 'draft' | 'published'
	/**
	 * Titre optimisé pour les moteurs de recherche (max 60 caractères)
	 */
	seo_title?: string | null
	/**
	 * Description optimisée pour les moteurs de recherche (max 155 caractères)
	 */
	seo_description?: string | null
	updatedAt: string
	createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
	id: number
	title: string
	/**
	 * URL de la galerie (ex: mariage-alice-tom)
	 */
	slug: string
	/**
	 * Description de la galerie
	 */
	description?: string | null
	category: 'mariage' | 'artistique' | 'nail-art' | 'evenementiel' | 'photo-video' | 'collections'
	/**
	 * Image principale affichée dans la liste des galeries
	 */
	coverImage: number | Media
	images: {
		image: number | Media
		caption?: string | null
		id?: string | null
	}[]
	publishedDate: string
	/**
	 * Lieu de l'événement (ex: Annecy, Haute-Savoie)
	 */
	location?: string | null
	status: 'draft' | 'published'
	/**
	 * Titre optimisé pour les moteurs de recherche (max 60 caractères)
	 */
	seo_title?: string | null
	/**
	 * Description optimisée pour les moteurs de recherche (max 155 caractères)
	 */
	seo_description?: string | null
	updatedAt: string
	createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
	id: number
	title: string
	/**
	 * URL du service (ex: maquillage-mariage)
	 */
	slug: string
	/**
	 * Résumé du service (affiché dans les cards)
	 */
	shortDescription: string
	description: {
		root: {
			type: string
			children: {
				type: any
				version: number
				[k: string]: unknown
			}[]
			direction: ('ltr' | 'rtl') | null
			format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
			indent: number
			version: number
		}
		[k: string]: unknown
	}
	category: 'maquillage' | 'nail-art' | 'evenementiel' | 'formation'
	/**
	 * Icône Tabler à afficher (ex: Sparkles, Heart, Camera)
	 */
	icon?: ('sparkles' | 'heart' | 'camera' | 'paint' | 'palette' | 'star' | 'crown' | 'diamond' | 'brush') | null
	featuredImage?: (number | null) | Media
	pricing?: {
		displayPricing?: boolean | null
		priceType?: ('fixed' | 'from' | 'quote') | null
		price?: number | null
		/**
		 * Détails supplémentaires sur la tarification
		 */
		priceDetails?: {
			root: {
				type: string
				children: {
					type: any
					version: number
					[k: string]: unknown
				}[]
				direction: ('ltr' | 'rtl') | null
				format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
				indent: number
				version: number
			}
			[k: string]: unknown
		} | null
	}
	features?:
		| {
				feature: string
				id?: string | null
		  }[]
		| null
	/**
	 * Durée estimée de la prestation (ex: 1h30, 2-3h)
	 */
	duration?: string | null
	/**
	 * Ordre d'affichage dans la liste (0 = premier)
	 */
	order: number
	status: 'draft' | 'published'
	/**
	 * Titre optimisé pour les moteurs de recherche (max 60 caractères)
	 */
	seo_title?: string | null
	/**
	 * Description optimisée pour les moteurs de recherche (max 155 caractères)
	 */
	seo_description?: string | null
	updatedAt: string
	createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
	id: number
	/**
	 * Ex: Sophie L., Julie M.
	 */
	name: string
	/**
	 * Le témoignage complet
	 */
	content: string
	/**
	 * Note sur 5
	 */
	rating: number
	source: 'google' | 'facebook' | 'instagram' | 'email' | 'other'
	/**
	 * Lien vers le commentaire original (optionnel)
	 */
	sourceUrl?: string | null
	/**
	 * Optionnel - photo de profil du client
	 */
	avatar?: (number | null) | Media
	/**
	 * Afficher en priorité ce témoignage
	 */
	featured?: boolean | null
	status: 'draft' | 'published'
	/**
	 * Ordre d'affichage dans la liste (0 = premier)
	 */
	order?: number | null
	updatedAt: string
	createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
	id: number
	document?:
		| ({
				relationTo: 'users'
				value: number | User
		  } | null)
		| ({
				relationTo: 'media'
				value: number | Media
		  } | null)
		| ({
				relationTo: 'blog'
				value: number | Blog
		  } | null)
		| ({
				relationTo: 'gallery'
				value: number | Gallery
		  } | null)
		| ({
				relationTo: 'services'
				value: number | Service
		  } | null)
		| ({
				relationTo: 'testimonials'
				value: number | Testimonial
		  } | null)
	globalSlug?: string | null
	user: {
		relationTo: 'users'
		value: number | User
	}
	updatedAt: string
	createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
	id: number
	user: {
		relationTo: 'users'
		value: number | User
	}
	key?: string | null
	value?:
		| {
				[k: string]: unknown
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null
	updatedAt: string
	createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
	id: number
	name?: string | null
	batch?: number | null
	updatedAt: string
	createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
	updatedAt?: T
	createdAt?: T
	email?: T
	resetPasswordToken?: T
	resetPasswordExpiration?: T
	salt?: T
	hash?: T
	loginAttempts?: T
	lockUntil?: T
	sessions?:
		| T
		| {
				id?: T
				createdAt?: T
				expiresAt?: T
		  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
	alt?: T
	updatedAt?: T
	createdAt?: T
	url?: T
	thumbnailURL?: T
	filename?: T
	mimeType?: T
	filesize?: T
	width?: T
	height?: T
	focalX?: T
	focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
	title?: T
	slug?: T
	featuredImage?: T
	excerpt?: T
	content?: T
	category?: T
	tags?:
		| T
		| {
				tag?: T
				id?: T
		  }
	publishedDate?: T
	author?: T
	status?: T
	seo_title?: T
	seo_description?: T
	updatedAt?: T
	createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
	title?: T
	slug?: T
	description?: T
	category?: T
	coverImage?: T
	images?:
		| T
		| {
				image?: T
				caption?: T
				id?: T
		  }
	publishedDate?: T
	location?: T
	status?: T
	seo_title?: T
	seo_description?: T
	updatedAt?: T
	createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
	title?: T
	slug?: T
	shortDescription?: T
	description?: T
	category?: T
	icon?: T
	featuredImage?: T
	pricing?:
		| T
		| {
				displayPricing?: T
				priceType?: T
				price?: T
				priceDetails?: T
		  }
	features?:
		| T
		| {
				feature?: T
				id?: T
		  }
	duration?: T
	order?: T
	status?: T
	seo_title?: T
	seo_description?: T
	updatedAt?: T
	createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
	name?: T
	content?: T
	rating?: T
	source?: T
	sourceUrl?: T
	avatar?: T
	featured?: T
	status?: T
	order?: T
	updatedAt?: T
	createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
	document?: T
	globalSlug?: T
	user?: T
	updatedAt?: T
	createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
	user?: T
	key?: T
	value?: T
	updatedAt?: T
	createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
	name?: T
	batch?: T
	updatedAt?: T
	createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
	id: number
	/**
	 * Titre optimisé pour les moteurs de recherche (max 60 caractères)
	 */
	seo_title?: string | null
	/**
	 * Description optimisée pour les moteurs de recherche (max 155 caractères)
	 */
	seo_description?: string | null
	hero: {
		title: string
	}
	about?: {
		title?: string | null
		image?: (number | null) | Media
		paragraphs?:
			| {
					text: string
					id?: string | null
			  }[]
			| null
	}
	services?: {
		title?: string | null
		subtitle?: string | null
	}
	blog?: {
		title?: string | null
		subtitle?: string | null
		limit?: number | null
	}
	gallery?: {
		title?: string | null
		subtitle?: string | null
		limit?: number | null
	}
	testimonials?: {
		enabled?: boolean | null
		title?: string | null
		subtitle?: string | null
		items?:
			| {
					name: string
					role: string
					content: string
					rating?: number | null
					id?: string | null
			  }[]
			| null
	}
	cta?: {
		title?: string | null
		subtitle?: string | null
	}
	updatedAt?: string | null
	createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
	seo_title?: T
	seo_description?: T
	hero?:
		| T
		| {
				title?: T
		  }
	about?:
		| T
		| {
				title?: T
				image?: T
				paragraphs?:
					| T
					| {
							text?: T
							id?: T
					  }
		  }
	services?:
		| T
		| {
				title?: T
				subtitle?: T
		  }
	blog?:
		| T
		| {
				title?: T
				subtitle?: T
				limit?: T
		  }
	gallery?:
		| T
		| {
				title?: T
				subtitle?: T
				limit?: T
		  }
	testimonials?:
		| T
		| {
				enabled?: T
				title?: T
				subtitle?: T
				items?:
					| T
					| {
							name?: T
							role?: T
							content?: T
							rating?: T
							id?: T
					  }
		  }
	cta?:
		| T
		| {
				title?: T
				subtitle?: T
		  }
	updatedAt?: T
	createdAt?: T
	globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
	[k: string]: unknown
}

declare module 'payload' {
	export interface GeneratedTypes extends Config {}
}
